language: csharp
dist: trusty
mono: none
dotnet: 1.0.1

script:
  - dotnet restore
  - dotnet build ./Lib -f netstandard1.1 -c Realease
  - dotnet build ./App -c Realease
  - dotnet test ./Tests/Tests.csproj -c Release